version: "3.9"
services:
  trino:
    ports:
      - "8080:8080"
    container_name: datalake-trino
    image: "trinodb/trino:410"
    volumes:
      - ./trino/etc:/usr/lib/trino/etc:ro
      - ./trino/catalog:/etc/trino/catalog
      - ./trino/etc/hive-site.xml:/etc/trino/hive-site.xml
      - ./mle2-lab1-91f7227387e4.json:/etc/trino/mle2-lab1-91f7227387e4.json
    depends_on:
      - hive-metastore
  
  metastore_db:
    container_name: datalake-metastore-db
    image: postgres:11
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore

  hive-metastore:
    container_name: datalake-hive-metastore
    image: 'starburstdata/hive:3.1.2-e.18'
    ports:
      - '9083:9083'
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore_db:5432/metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_WAREHOUSE_DIR: gs://mle_lab1_bucket/
      GOOGLE_APPLICATION_CREDENTIALS: /opt/hive/conf/mle2-lab1-91f7227387e4.json
      S3_ENDPOINT: ""
      S3_ACCESS_KEY: ""
      S3_SECRET_KEY: ""
      S3_PATH_STYLE_ACCESS: ""
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
    volumes:
      - ./trino/etc/hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./mle2-lab1-91f7227387e4.json:/opt/hive/conf/mle2-lab1-91f7227387e4.json
    depends_on:
      - metastore_db
  
  offline-fs:
    container_name: datalake-offline-fs
    image: postgres:11
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: k6
      POSTGRES_PASSWORD: k6
      POSTGRES_DB: k6

volumes:
  minio_storage:
